name: Atualizar Feed RSS DRE

on:
  schedule:
    # Executar diariamente às 8:00 UTC
    - cron: "0 8 * * *"
  workflow_dispatch:
    # Permitir execução manual

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directories
        run: |
          mkdir -p RSS
          mkdir -p data

      - name: Run RSS extractor
        run: |
          cd scripts
          python rss_dre_extractor.py
        env:
          # Configurar timezone para Portugal
          TZ: Europe/Lisbon

      - name: Check if files were created
        run: |
          echo "Checking created files:"
          ls -la RSS/
          ls -la data/
          echo "RSS file size:"
          wc -l RSS/feed_rss_procedimentos.xml || echo "RSS file not found"
          echo "Ativos file size:"
          wc -l data/ativos.json || echo "Ativos file not found"

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add RSS/
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "🔄 Atualizar feed RSS DRE e procedimentos ativos - $(date +'%Y-%m-%d %H:%M:%S')" && git push)
